---
- hosts: webserver
  sudo: yes

  vars:

  tasks:

  - name: delete html file 
    file:
      path: /var/ww/html/EntSWPlatforms
      state: absent

  - name: uninstall apache
    apt:
      name: apache2
      state: absent
      update_cache: yes
      purge: yes
